config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'rocks#index'

  resources :rocks, only: [:new, :create, :show, :index , :destroy ]  do
    resources :requests, only: [:create]
  end

  resources :requests, only: [:show] do
    member do
      patch :decline
      patch :accept
      patch :cancel
    end
  end

  get 'dashboard', to: 'users#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :rock
  belongs_to :user
  validates :date, :end_date, presence: true
end

app/models/rock.rb
class Rock < ApplicationRecord
  belongs_to :user
  has_many :requests, dependent: :destroy
  has_one_attached :photo
  validates :name, :color, :shape, :price, presence: true

  COLORS = [:blue, :red, :yellow, :black, :grey, :green, :white]
  SHAPES = [:round, :pointy, :big, :sharp]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rocks
  has_many :requests

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    @requests = Request.all
  end

  def create
    @request = Request.new(request_params)
    @rock = Rock.find(params[:rock_id])
    @user = current_user
    @request.rock = @rock
    @request.user = @user
    @request.save!
    redirect_to request_path(@request)

  end

  def show
    # @rock = Rock.find(params[:id])
    @request = Request.find(params[:id])
    @rentduration = @request.end_date - @request.date + 1

  end


  def decline
    @request = Request.find(params[:id])
    @request.status = "Refusée"
    @request.save
    redirect_to dashboard_path
  end

  def accept
    @request = Request.find(params[:id])
    @request.status = "Acceptée"
    @request.save
    redirect_to dashboard_path
  end


  private

  def request_params
    params.require(:request).permit(:date, :end_date)
  end
end

app/controllers/rocks_controller.rb
class RocksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @rocks = Rock.all

  end

  def new
    @rock = Rock.new
  end

  def create
    @rock = Rock.new(rock_params)
    @rock.user = current_user
    if @rock.save
      redirect_to rock_path(@rock)
    else
      render :new
    end
  end

  def show
    @rock = Rock.find(params[:id])
    @user = @rock.user
    @user.geocode
    @markers = [{
        lat: @user.latitude,
        lng: @user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { user: @user }),
        image_url: helpers.asset_url("moai-icon-red.png")
      }]
      @request = Request.new
  end

  def update
    @rock = Rock.find(params[:id])
    @rock.update(rock_params)
    redirect_to rock_path(@rock)
  end

  def destroy
    @rock = Rock.find(params[:id])
    @rock.requests.delete_all
    @rock.delete
    redirect_to dashboard_path
  end

  private

  def rock_params
    params.require(:rock).permit(:name, :description, :shape, :color, :price, :user_id, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def dashboard
@rocks = current_user.rocks
@requests = current_user.requests
@pastrequests = current_user.requests.select { |request|  request.status == "Refusée" || request.end_date < Date.today   }
@rents = Request.where({ rock_id: @rocks})
@urgentrents = @rents.where({ status: "En attente de validation"})
@okrents = @rents - @urgentrents

end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RockyAloha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="assets/css/style.css">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>



  <body>


            <div class="navbar navbar-expand-sm navbar-light navbar-rockyaloha">
            <div class="container-fluid">
              <a class="navbar-brand" href=<%= rocks_path %>>
                <%= image_tag "moaibanner.png", id: "logo-navbar" %>
              </a>
              <div class="nav-item">
                <a class="btn-semi-ghost" href=<%= new_rock_path %>>Partagez votre caillou</a>
              </div>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

    <%= render 'shared/flashes' %>


              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto">

                    <li class="nav-item dropdown">
                      <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://res.cloudinary.com/dwcmq45ak/image/upload/v1653314090/MoerakiBouldersSunrise_hpd1ny.png" />
                      <% if user_signed_in? && Request.where({rock_id: current_user.rocks}).where({status: "En attente de validation"}).count > 0 %>
                        <p class="position-absolute top-100 end-50 translate-middle badge rounded-pill bg-danger"> <%= Request.where({rock_id: current_user.rocks}).where({status: "En attente de validation"}).count %> </p>
                      <% end %>
                      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <% if user_signed_in? %>
                          <a class="dropdown-item" <%=link_to('Dashboard', dashboard_path)%> </a>
                          <a class="dropdown-item" <%=link_to('Logout', destroy_user_session_path, :method => 'delete')%> </a>
                            <% else %>
                          <a class="dropdown-item" href=<%= new_user_session_path %>>Connexion</a>
                        <% end %>
                      </div>
                    </li>
                </ul>
              </div>
            </div>
          </div>


    <%= yield %>

<div class="footer row">
  <div class="footer-links col">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright col text-right">
    Ce site est fait avec <i class="fas fa-heart"></i> depuis Nantes!
  </div>
</div>


    <%= render 'shared/flashes' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="landing-container" >

  <div class="d-flex" >
    <div class="landing-text d-flex flex-column justify-content-center text-center">
      <%= image_tag "landinglogotransparent.png", class: "bounce-top w-25 mx-auto" %>
      <h4> Anniversaire, mariage, barmitzvah...</h4>
      <h3>Pour chaque occasion, trouvez votre caillou.</h3>
      <a class="btn btn-flat btn-primary w-50 mx-auto mt-5" href="<%= rocks_path %>">Je veux mon caillou</a>
  </div>
  <div class="landing-pic" style="background-image: url('<%= image_path("landingbanner.jpg") %>')">
  </div>
</div>

app/views/requests/show.html.erb
<div class="container", style="text-align: center; padding-top:30px; padding-bottom:0px;">
 <h2>Votre réservation</h2>
  <div class="wrapper", style="margin-top:10px; text-align: left;">
    <div class="product-img">
      <img src= <%=  cl_image_path(@request.rock.photo.key)%> height="420" width="420">
    </div>

    <div class="product-info", style="width: 50%;">
      <div class="product-title mx-4 mt-4">
        <h1><%= @request.rock.name.capitalize %></h1>
        <div class="product-price text-right mx-4">
          <p><%= @request.rock.price %>€/jour</p>
        </div>
      </div>
      <div class="product-text">
        <h2><i class="bi bi-heptagon m-4"></i><%= @request.rock.shape %></h2>
        <h2><i class="bi bi-palette m-4"></i><%= @request.rock.color %></h2>
        <h2><i class="bi bi-geo-alt m-4"></i><%= @request.rock.user.address %></h2>
        <h2><i class="bi bi-person m-4"></i><%= @request.user.first_name %></h2>
        <div class="border mx-5 p-3 mt-5", style="text-align: center">
          <h5 class="badge bg-secondary"><%= @request.status %></h5><br>
          <% if current_user == @request.rock.user && @request.status == "En attente de validation"%>
          <%= link_to "accepter", accept_request_path(@request), :method => 'patch', class: "btn btn-outline-success mx-3", remote: true %>  <%= link_to "refuser", decline_request_path(@request), :method => 'patch', class: "btn btn-outline-danger mx-3", remote: true %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-group-row" style="width: 300px; text-align: center; margin-top: auto; margin-bottom: auto">
        <h2><i class="bi bi-calendar"></i></h2>
        <h4><%= @request.date.strftime("%d/%m/%Y") %></h4>
        <h5>au</i></h5><h4><%= @request.end_date.strftime("%d/%m/%Y") %></h4>
        ----------
        <h5><%= @rentduration.to_i %>  jours</h5>
        soit

        <h3 style="margin-top: 10px;"><%= @rentduration.to_i * @request.rock.price%> €</h3>
    </div>
  </div>
  <div class="map">
    <%# Contenu Mapbox Setup %>
    <div style="width: 100%; height: 600px;" class="my-5"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
</div>




<div class = "container-fluid justify-content-between" >

  <div >
    <% if current_user == @request.rock.user && @request.status == "En attente de validation"%>
    <%= link_to "accepter", accept_request_path(@request), :method => 'patch' %> / <%= link_to "refuser", decline_request_path(@request), :method => 'patch' %>
    <% end %>
  </div>
</div>

app/views/rocks/_info_window.html.erb
<h2><%= user.name %></h2>
<p><%= user.address %></p>

app/views/rocks/create.html.erb
<h1>Rocks#create</h1>
<p>Find me in app/views/rocks/create.html.erb</p>

app/views/rocks/index.html.erb
<%# <div class="container-fluid col-12"> %>
  <div class="banner">
    <div class="container">
      <h1>Allergique aux animaux et pas la main verte ? <br> Faites d'une <strong>pierre</strong> 2 coups et louez un <strong>caillou</strong>!</h1>
        <%= link_to "Trouvez le caillou idéal!", "#top", class: "btn btn-ghost-banner mt-3"%>
    </div>
  </div>


  <div class="container-fluid container py-3 mt-4" id="top">
    <div class="row mt-4">
      <% @rocks.each do |rock| %>
      <div class="col-md-3">
      <%= link_to rock_path(rock), :action => 'get' do %>
        <div class="card mb-3 border-0">
          <img src= <%=  cl_image_path(rock.photo.key, height: 300) %> class="card-img-top" alt="...">
              <div class="card-body rounded-bottom">
              <div class="title-price-index">
                <h5> <%= rock.name.capitalize %> </h5>
                <div class="product-price-index">
                    <p><%= rock.price %>€/j</p>
                </div>
              </div>
                  <div class="product-text-index">
                    <h2><i class="bi bi-heptagon m-1"></i><%= rock.shape %></h2>
                    <h2><i class="bi bi-palette m-1"></i><%= rock.color %></h2>
                    <h2><i class="bi bi-geo-alt m-1"></i><%= rock.user.address.split.last %></h2>
                  </div>
              </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
<%# </div> %>

app/views/rocks/new.html.erb
<div class="container responsive-form formidable">
  <h1>Partager votre cailloux!</h1>

  <%= simple_form_for [@rock] do |f| %>
    <%= f.input :name, label: 'Nom' %>
    <%= f.input :color,:collection => [:bleu, :rouge, :jaune, :noir, :gris, :violet, :blanc], label: 'Couleur' %>
    <%= f.input :shape,:collection => [:rond, :pointu, :grand, :aiguisé], label: 'Forme' %>
    <%= f.input :price, label: 'Prix' %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <div class="d-grid mx-auto">
      <%= f.button:submit, 'Créer mon cailloux!', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/rocks/show.html.erb
<%# product info and price %>
<div class="container">
  <div class="booking-wrapper row">
    <div class="product-img col">
      <img src= <%=  cl_image_path(@rock.photo.key)%> height="420" width="420" class="img-show">
    </div>

    <div class="product-info col">
      <div class="product-title mx-4 mt-4">
        <h1><%= @rock.name.capitalize %></h1>
        <div class="product-price text-right mx-4">
          <p><%= @rock.price %>€/jour</p>
        </div>
      </div>
      <div class="product-text">
        <h2><i class="bi bi-heptagon m-4"></i><%= @rock.shape %></h2>
        <h2><i class="bi bi-palette m-4"></i><%= @rock.color %></h2>
        <h2><i class="bi bi-geo-alt m-4"></i><%= @rock.user.address %></h2>
        <h2><i class="bi bi-person m-4"></i><%= @rock.user.first_name %></h2>
        <div class="border mx-5 p-3 mt-5">
          <p><%= @rock.description %></p>
        </div>
      </div>
    </div>

    <div class="form-group-row m-4 col">
      <% if user_signed_in? %>
        <%= simple_form_for [@rock, @request] do |f| %>
        <%= f.error_notification %>
        <%= f.input :date, html5: true, label: 'Début' %>
        <%= f.input :end_date, html5: true, label: 'Fin' %>
        <%= f.button :submit, 'Réserver!', class: "btn-primary"%>
        <% end %>
      <% else %>
      <div class="log-in-button-show">
        <%= link_to "Enregistrez vous et louez ce caillou!", new_user_session_path, class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="map row">
    <%# Contenu Mapbox Setup %>
    <div class="my-5"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<div class="data" data-controller="dashboard">

<div class="d-flex text-center justify-content-center" id="interfacebtn">
  <% if current_user.rocks.exists? %>
    <button class="btn nofocus btn-outline-primary btn-lg text-center" data-dashboard-target="propriobtn" data-action="click->dashboard#toggleToProprio">
      Mes cailloux
    </button>

    <button class="btn nofocus btn-outline-secondary btn-lg text-center" data-dashboard-target="loueurbtn" data-action="click->dashboard#toggleToLoueur">
      Mes locations
    </button>
  <% end %>
</div>

<div class="d-flex justify-content-center flex-wrap" id="proprio" data-dashboard-target="proprio">
  <% if current_user.rocks.exists? %>
    <div>
    <% if @urgentrents.exists? %>
        <div id="myurgentrents">
            <h2>Demandes à traiter</h2>

              <% @urgentrents.each do |rent| %>
              <%= link_to request_path(rent), :action => 'get' do %>
                  <div class="dash-product" style="height: 50px; width: auto; text-align: center;">
                    <img src=<%= cl_image_path(rent.rock.photo.key) %> />
                    <div class="dash-product-infos" >
                       <i class="bi bi-person"></i>  <%= rent.user.first_name %>
                       <i class="bi bi-calendar"></i> Du <%= rent.date.strftime("%d/%m/%Y") %> au <%= rent.end_date.strftime("%d/%m/%Y") %>
                       <i class="bi bi-coin"></i> <b> <%= (rent.end_date - rent.date + 1).to_i * rent.rock.price %> €</b>
                       <%= link_to "✔️", accept_request_path(rent), :method => 'patch' %>
                       <%= link_to "❌", decline_request_path(rent), :method => 'patch' %>
                    </div>
                  </div>
              <% end %>
              <% end %>
          </div>
      <%end%>

      <div id="myrocks" class= "d-flex">
        <div id="mycollection">
        <h2>Mes cailloux</h2>
        <div class="container-fluid container py-3 mt-4" id="top">
          <div class="d-flex">
            <% @rocks.each do |rock| %>
            <div class="mx-3 ">
            <%= link_to rock_path(rock), :action => 'get' do %>
              <div class="card mb-3 border-0" id="cardinv">
                <img src= <%=  cl_image_path(rock.photo.key, height: 300) %> class="card-img-top" alt="...">
                    <div class="card-body rounded-bottom">
                    <div class="title-price-index">
                      <h5> <%= rock.name.capitalize %> </h5>
                      <div class="product-price-index">
                          <p><%= rock.price %>€/j</p>
                      </div>
                    </div>
                        <div class="product-text-index" style="text-align: left;">
                          <h5><i class="bi bi-graph-up-arrow"></i> <%= rock.requests.where({ status: "Acceptée"}).count %></h5>
                          <h5 class="dash-title"><%= link_to "🗑️", rock_path(rock.id), id: "deletebtn", method: :delete, remote: true, data: {confirm: "Etes vous sur ?"} %></h5>
                        </div>
                    </div>
              </div>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        </div>

        <div id="myrents">
            <h2>Historique des demandes</h2>
            <ul class="justify-content-center">
              <% @okrents.each do |rent| %>
                <%= link_to request_path(rent), :action => 'get' do %>
                <li>
                   <div class="dash-product">
                  <img src=<%= cl_image_path(rent.rock.photo.key) %> />
                  <div class="dash-product-infos">
                    <span class="badge bg-secondary"><%= rent.status %></span>
                     <i class="bi bi-person"></i> <%= rent.user.first_name %><br>
                     <i class="bi bi-calendar"></i> <%= rent.date.strftime("%d/%m/%Y") %> - <%= rent.end_date.strftime("%d/%m/%Y") %>
                   </div>
                   </div>
                </li>
                <% end %>
              <% end %>
            </ul>
          </div>

      </div>


    </div>
    <%end%>
</div>



<% if current_user.rocks.exists? %>
<div class="container  d-none" id="loueur" data-dashboard-target="loueur" >
<% else %>
<div class="container" id="loueur" data-dashboard-target="loueur" >
<% end %>
    <h2>Mes réservations</h2>
    <% unless @requests.empty? %>
          <% @requests.each do |request| %>
          <%= link_to request_path(request), :action => 'get' do %>
                   <div class="dash-product mx-auto" style="width: 50%;">
                      <img src=<%= cl_image_path(request.rock.photo.key) %> />
                      <div class="dash-product-infos mx-auto">
                        <h2><%= request.rock.name %></h2>
                        <h2><span class="badge bg-secondary"><%= request.status %></span></h2>
                        Du <%= request.date.strftime("%d/%m/%Y") %> au <%= request.end_date.strftime("%d/%m/%Y") %>
                        <h2><%= link_to "Voir les détails", request_path(request) %></h2>
                      </div>
                   </div>
            <% end %>
          <% end %>
    <% else %>
    <div id="norent">
      <%= image_tag "sadrock.jpg", class: "sadrock" %>
      <p> Vous n'avez réservé aucun caillou :(</p>
      <%=link_to "Trouvez le caillou de vos rêves", rocks_path, class: "btn btn-primary mb-2 col-6" %>
     </div>
    <% end %>
</div>
</div>